name: Build WD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Install VCPkg Packages
      uses: lukka/run-vcpkg@v11

    - name: Cache Cmake
      uses: actions/cache@v5
      with: 
        path: build
        key: cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: cmake-
    
    - name: Configure CMake
      run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cd ../
          where.exe cppwinrt
          Get-Content "projects/WinDurango.Kinect/Generated Files/winrt/Windows.Kinect.h" | Select-Object -First 10
          Get-Content "build/vcpkg_installed/x64-windows/include/winrt/base.h" | Select-Object -First 15

    - name: Build WinDurango
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: WinDurango-Release
        path: build/bin/Release/
        archive: true
