name: Build WinDurango

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    name: Build (${{ matrix.configuration }})
    continue-on-error : ${{matrix.continue}} 
    strategy:
      fail-fast: true
      matrix:
        configuration: [Debug]
        continue: [false]
        include:
          - configuration: Release
            continue: true

    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v4    
    
    - uses: ChristopheLav/windows-sdk-install@v1
      with:
        version-sdk: 28000
        features: 'OptionId.UWPCPP,OptionId.DesktopCPParm64'

    - uses: ilammy/msvc-dev-cmd@v1
      with: 
        sdk: 10.0.28000.0

    - name: Install VCPkg Packages
      uses: lukka/run-vcpkg@v11

    - name: Cache Cmake
      uses: actions/cache@v5
      with: 
        path: build
        key: cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: cmake-
    
    - name: Configure CMake
      run: |
          New-Item -ItemType Directory -Force -Path build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cd ../

    - name: Build WinDurango
      run: cmake --build build --config ${{ matrix.configuration }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: WinDurango-${{ matrix.configuration }}
        path: build/bin/${{ matrix.configuration }}/
        archive: true
